routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\AdvertisingpackagesController;
use App\Http\Controllers\Admin\AdvertismentController;
use App\Http\Controllers\Admin\BannersController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\HelpController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CitiesController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PropagandaController;
use App\Http\Controllers\Admin\TermsController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::POST('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {


            Route::get('complaints', [ComplaintController::class, 'index'])->name('complaints');
            Route::delete('complaints/{id}', [ComplaintController::class, 'destroy'])->name('destroycomplaints');

            Route::resource('roles', RoleController::class)->except(['show']);

            Route::resource('services', ServicesController::class)->except(['show']);
            Route::get('serviceactive', [ServicesController::class, 'ServiceStatus'])->name('serviceactive');

            Route::resource('banners', BannersController::class)->except(['show']);
            Route::get('banneractive', [BannersController::class, 'BannerStatus'])->name('banneractive');

            Route::resource('advertisments', AdvertismentController::class)->except(['show']);
            Route::get('advertismentactive', [AdvertismentController::class, 'advertismentStatus'])->name('advertismentactive');

            Route::resource('admins', AdminsController::class)->except(['show']);
            Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

            Route::resource('cities', CitiesController::class)->except(['show']);
            Route::get('cityactive', [CitiesController::class, 'CityStatus'])->name('cityactive');
            
            Route::resource('packages', AdvertisingpackagesController::class)->except(['show']);
            Route::get('packageactive', [AdvertisingpackagesController::class, 'packageStatus'])->name('packageactive');

            Route::get('helps', [HelpController::class, 'index'])->name('helping');
            Route::post('helps', [HelpController::class, 'update'])->name('updatehelping');

            Route::get('terms', [TermsController::class, 'index'])->name('terming');
            Route::post('terms', [TermsController::class, 'update'])->name('updateterming');

            Route::get('propagandas', [PropagandaController::class, 'index'])->name('propaganding');
            Route::post('propagandas', [PropagandaController::class, 'update'])->name('updatepropaganding');

            Route::resource('users', UsersController::class)->except(['show']);
            Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');
            Route::get('useraddress', [UsersController::class, 'UserAddress'])->name('useraddress');

            Route::resource('owners', OwnerController::class);
            Route::get('owneractive', [OwnerController::class, 'OwnerStatus'])->name('owneractive');
           // Route::resource('balance/{id}', [BalanceOwnerController::class, 'destroy']);
            Route::get('ownersbalance/{id}',[OwnerController::class,'OwnersBalance'])->name('owners.balances');


            Route::resource('contactus', ContactController::class)->except(['create','edit']);


            Route::get('about', [AboutController::class, 'index'])->name('about');
            Route::post('about', [AboutController::class, 'update'])->name('updateabout');

        });  

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/API/OwnerController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Resources\OwnerResource as OwnerResource;
use App\Models\Owner;
use App\Models\Rate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OwnerController extends Controller
{

    public function index()
    {
        $owners = Owner::where('active',true)->with('services')->get();
        
        //dd($owners);
        if($owners){
            return response()->json([ 
                'message'=>'success',
                'owners' => OwnerResource::collection($owners),
                ],200);
        }
    }


    public function ownerDetails(Request $request){

        $owner_id = $request->id;
        $owner = Owner::where(['id'=>$owner_id,'active'=>true])->first();
        // $avgRate = Rate::avg('rate');
        $rate = DB::table('rates')
        ->where('owner_id', $owner_id)
        ->avg('rate');
        $rateaverage = (int)$rate;
            return response()->json([ 
                'status'=>'success',
                'owner_id' => $owner->id,
                'owner_image' => $owner->image,
                'owner_name' => $owner->name,
                'owner_phone' => $owner->phone,
                'owner_service' =>  [
                    'id' => $owner->services->id,
                    'name_ar' => $owner->services->translate('ar')->name,
                    'name_en' => $owner->services->translate('en')->name,
                ],
                'owner_city' =>  [
                    'id' => $owner->cities->id,
                    'name_ar' => $owner->cities->translate('ar')->name,
                    'name_en' => $owner->cities->translate('en')->name,
                ],
                'owner_name' => $owner->name,
                'avilable_from' => $owner->from,
                'avilable_to' => $owner->to,
                'min_salary' => $owner->min_salary,
                'rate' =>$rateaverage
            ],200);
    }
}

app/Http/Controllers/Admin/OwnerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreOwner;
use Illuminate\Support\Facades\Storage;
use App\Models\City;
use App\Models\Owner;
use App\Models\OwnerService;
use App\Models\Service;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Http\Request;

class OwnerController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:owners-read')->only(['index']);
        $this->middleware('permission:owners-create')->only(['create', 'store']);
        $this->middleware('permission:owners-update')->only(['edit', 'update']);
        $this->middleware('permission:owners-delete')->only(['destroy']);
    }



    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Owner::get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('image', function ($query) {
                return '<img src=' . $query->image_path . ' border="0" style=" width: 80px; height: 80px;" class="image-show img-circle" />';
            })
            ->editColumn('active', function ($query) {
                if ($query->active) {
                    $btn = '
            <div align="center">
            <label class="switch">
            <input data-id="' . $query->id . '" type="checkbox" id="check" checked>
                <div class="slider round">
                    <span class="on">ON</span>
                    <span class="off">OFF</span>
                </div>
            </label>
         </div>';
                } else {
                    $btn = '
                <div align="center">
                <label class="switch">
                <input data-id="' . $query->id . '" type="checkbox" id="check">
                    <div class="slider round">
                        <span class="on">ON</span>
                        <span class="off">OFF</span>
                    </div>
                </label>
            </div>';
                }

                return $btn;
            })
            ->addColumn('action', function($row){
                
            if (Auth::guard('admin')->user()->hasPermission('owners-update')){
            $btn ='<a href="' .route("owners.edit", $row->id). '" type="button" class="btn btn-info btn-icon"><i class="icofont icofont-pen-alt-4"></i></i></a> &nbsp;';
            }else{
             $btn = '<a href="" class="btn btn-primary btn-xs disabled">Edit</i></a>';
            }

            if (Auth::guard('admin')->user()->hasPermission('owners-read')){
                $btn =  $btn .'<a href="' .route("owners.show", $row->id). '" type="button" class="btn btn-default btn-icon waves-effect" ><i class="icofont icofont-eye-alt"></i></a> &nbsp;';
            }else{
                $btn =   $btn .'<a href="" class="btn btn-primary btn-xs disabled">Show</i></a>';
            }

            if (Auth::guard('admin')->user()->hasPermission('owners-read')){
                $btn =  $btn .'<a href="' .route("owners.balances", $row->id). '" type="button" class="btn btn-default btn-icon waves-effect" ><i class="icofont-coins"></i></a> &nbsp;';
            }else{
                $btn =   $btn .'<a href="" class="btn btn-default btn-icon waves-effect disabled">Show</i></a>';
            }
    
            if (Auth::guard('admin')->user()->hasPermission('owners-delete')){
                $btn = $btn.
                '<form class="delete"  action="' . route("owners.destroy", $row->id) . '"  method="POST" id="delform"
                style="display: inline-block; right: 50px;" >
                <input name="_method" type="hidden" value="DELETE">
                <input type="hidden" name="_token" value="' . csrf_token() . '">
                <button type="submit" class="btn btn-danger btn-icon" title=" ' . 'Delete' . ' "><i class="icofont icofont-trash"></i></button>
                    </form>';
            }else{
                $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
            }

                        return $btn;
                    })

                    ->rawColumns(['action','active','image'])
                    ->make(true);

        }

        return view('admin.owners.index');
    }

    public function create()
    {
        $cities = City::all();
        $services = Service::where('parent_id',null)->get();
        return view('admin.owners.create', compact('cities','services'));
    }

    public function store(StoreOwner $request)
    {
        $owner = Owner::create([
            'name'       => $request->input('name'),
            'email'      => $request->input('email'),
            'phone'      => $request->input('phone'),
            'commerical' => $request->input('commerical'),
            'address'    => $request->input('address'),
            'min_salary' => $request->input('min_salary'),
            'service_id' => $request->input('service_id'),
            'city_id'    => $request->input('city_id'),
            'from'       => $request->input('from'),
            'to'         => $request->input('to'),
            'bank_name'         => $request->input('bank_name'),
            'bank_account_owner'=> $request->input('bank_account_owner'),
            'account_number'    => $request->input('account_number'),
            'password'   => Hash::make($request->password),
        ]);

        if ($request->image) {
            Image::make($request->image)->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/owners/' . $request->image->hashName()));

            $owner->image = 'uploads/owners/' . $request->image->hashName();
        }

        if ($request->image_owner) {
            Image::make($request->image_owner)->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/owners/' . $request->image_owner->hashName()));

            $owner->image ='uploads/owners/' . $request->image_owner->hashName();
        }

       $owner->save();

       return response()->json(['status'=>'success','data'=>$owner]);
    }

 

    public function show($id)
    {
        // $owner = Owner::findOrFail($id);
        // $services = OwnerService::get();
        // return view('admin.owners.show',compact('owner','services'));
    }

    public function OwnersBalance($id){
        return view('admin.owners.balance');
    }


    public function OwnerStatus(Request $request)
    {
        $owner = Owner::find($request->owner_id);
        $owner->active = $request->active;
        $owner->save();
        
        return response()->json(['status' => 'success', 'data' => $owner]);
    }



    public function edit($id)
    {
        $services = Service::where('parent_id',null)->get();

        $owner = Owner::findOrFail($id);
        return view('admin.owners.edit',compact('owner','services'));
    }



    public function update(Request $request, $id)
    {
        $owner = Owner::findOrFail($id);

        $owner->update([
            'name'           => $request->input('name'),
            'phone'          => $request->input('phone'),
            'address'        => $request->input('address'),
            'from'           => $request->input('from'),
            'to'             => $request->input('to'),
            'min_salary'     => $request->input('min_salary'),
            'national_number'=> $request->input('national_number'),
            'service_id'     => $request->input('service_id'),
            'city_id'        => $request->input('city_id'),
            'from'           => $request->input('from'),
            'to'             => $request->input('to'),
            'bank_name'         => $request->input('bank_name'),
            'bank_account_owner'=> $request->input('bank_account_owner'),
            'account_number'    => $request->input('account_number'),
            'password'       => Hash::make($request->password),
        ]);

        if ($request->image) {
            Image::make($request->image)->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/owners/' . $request->image->hashName()));

            $owner->image = 'uploads/owners/' . $request->image->hashName();
        }
        if ($request->image_owner) {
            Image::make($request->image_owner)->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })->save(public_path('uploads/owners/' . $request->image_owner->hashName()));

            $owner->image_owner = 'uploads/owners/' . $request->image_owner->hashName();
        }

        $owner->save();
        return response()->json(['status'=>'success','data'=>$owner]);
    }



    public function destroy($id)
    {
        $user = Owner::findOrFail($id);

        if ($user->image != 'default.png') {
            Storage::disk('public_uploads')->delete('/owners/' . $user->image);
        }
            
        $user->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/owners/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
            <div class="page-header">
                <div class="page-header-title">
                    <h4> @lang('admin.owners') </h4>
                </div>
                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a href="">
                                <i class="icofont icofont-home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.owners')</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.editowners')</a>
                        </li>
                    </ul>
                </div>
            </div>
      <!-- Page body start -->
      <div class="page-body">
        <div class="row">
            <div class="col-sm-8">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>@lang('admin.editowners')</h5>
                    </div>
                    <div class="card-block">
                        <form id="owners" method="POST" data-parsley-validate>
                            @csrf
                            @method('put')
                            <input type="hidden" name="OwnerId" id="owner_id" value="{{$owner->id}}"  class="form-control">

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.companyname')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="name"
                                        placeholder="@lang('admin.companyname')" value="{{$owner->name}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.companyphone')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="phone"
                                        placeholder="@lang('admin.companyphone')" value="{{$owner->phone}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.email')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="email"
                                        placeholder="@lang('admin.email')" value="{{$owner->email}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.services')</label>
                                <div class="col-sm-10">
                                <select id="hello-single" name="service_id" class="form-control form-control-round">
                                    <option value="">---</option>
                                    @foreach ($services as $service)
                                    <option value="{{$service->id}}" @if($service->id == $owner->service_id) selected @endif>{{$service->name}}</option>
                                    @endforeach
                                </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.commerical')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="commerical"
                                        placeholder="@lang('admin.commerical')" value="{{$owner->commerical}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.min_salary')</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control form-control-round" name="min_salary"
                                        placeholder="@lang('admin.min_salary')" value="{{$owner->min_salary}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.from')</label>
                                <div class="col-sm-10">
                                    <input type="time" class="form-control form-control-round" name="from"
                                        value="{{$owner->from}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.to ')</label>
                                <div class="col-sm-10">
                                    <input type="time" class="form-control form-control-round" name="to"
                                    value="{{$owner->to}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.bank')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="bank_name"
                                    value="{{$owner->bank_name}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.acountowner')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="bank_account_owner"
                                    value="{{$owner->bank_account_owner}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.accountnumber')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control form-control-round" name="account_number"
                                    value="{{$owner->account_number}}" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.password')</label>
                                <div class="col-sm-10">
                                    <input type="password" name="password" value="{{old('password')}}"  class="form-control form-control-round" placeholder="Enter Admin Password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.address')</label>
                                <div class="col-sm-10">
                                    <textarea name="address" class="form-control form-control-round" id="" cols="10" rows="5"
                                    required>{{$owner->address}}</textarea>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.image')</label>
                                <input type="file" name="image" id="image" value="{{$owner->image}}" class="filestyle image" data-buttonname="btn-primary" >
                                <div class="form-group col-md-6">
                                    <img src="{{$owner->image_path}}" 
                                    width="250" height="130" alt="" 
                                    style="margin-right: 50px;" 
                                    class="image-show"/>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.image_owner')</label>
                                <input type="file" name="image_owner" id="image_owner" value="{{$owner->image_owner}}" class="filestyle image_owner" data-buttonname="btn-primary" >
                                <div class="form-group col-md-6">
                                    <img src="{{$owner->image_path}}" 
                                    width="250" height="130" alt="" 
                                    style="margin-right: 50px;" 
                                    class="image_owner-show"/>
                                </div>
                            </div>

                            <div class="form-group has-danger row">
                                <div class="col-sm-10">
                        <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                        &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                        <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Basic Form Inputs card end -->
            </div>
        </div>
    </div>
    </div>
</div>

@endsection
@push('js')
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#owners',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#owner_id').val();
                 var url = '{{ route('owners.update', ':id') }}';
                 url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {
                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }

                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush