routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\AdvertisingpackagesController;
use App\Http\Controllers\Admin\AdvertismentController;
use App\Http\Controllers\Admin\BannersController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\HelpController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CitiesController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PropagandaController;
use App\Http\Controllers\Admin\TermsController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::POST('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {


            Route::get('complaints', [ComplaintController::class, 'index'])->name('complaints');
            Route::delete('complaints/{id}', [ComplaintController::class, 'destroy'])->name('destroycomplaints');

            Route::resource('roles', RoleController::class)->except(['show']);

            Route::resource('services', ServicesController::class)->except(['show']);
            Route::get('serviceactive', [ServicesController::class, 'ServiceStatus'])->name('serviceactive');

            Route::resource('banners', BannersController::class)->except(['show']);
            Route::get('banneractive', [BannersController::class, 'BannerStatus'])->name('banneractive');

            Route::resource('advertisments', AdvertismentController::class)->except(['show']);
            Route::get('advertismentactive', [AdvertismentController::class, 'advertismentStatus'])->name('advertismentactive');

            Route::resource('admins', AdminsController::class)->except(['show']);
            Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

            Route::resource('cities', CitiesController::class)->except(['show']);
            Route::get('cityactive', [CitiesController::class, 'CityStatus'])->name('cityactive');
            
            Route::resource('packages', AdvertisingpackagesController::class)->except(['show']);
            Route::get('packageactive', [AdvertisingpackagesController::class, 'packageStatus'])->name('packageactive');

            Route::get('helps', [HelpController::class, 'index'])->name('helping');
            Route::post('helps', [HelpController::class, 'update'])->name('updatehelping');

            Route::get('terms', [TermsController::class, 'index'])->name('terming');
            Route::post('terms', [TermsController::class, 'update'])->name('updateterming');

            Route::get('propagandas', [PropagandaController::class, 'index'])->name('propaganding');
            Route::post('propagandas', [PropagandaController::class, 'update'])->name('updatepropaganding');

            Route::resource('users', UsersController::class)->except(['show']);
            Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');
            Route::get('useraddress', [UsersController::class, 'UserAddress'])->name('useraddress');

            Route::resource('owners', OwnerController::class);
            Route::get('owneractive', [OwnerController::class, 'OwnerStatus'])->name('owneractive');
           // Route::resource('balance/{id}', [BalanceOwnerController::class, 'destroy']);
            Route::get('ownersbalance/{id}',[OwnerController::class,'OwnersBalance'])->name('owners.balances');


            Route::resource('contactus', ContactController::class)->except(['create','edit']);


            Route::get('about', [AboutController::class, 'index'])->name('about');
            Route::post('about', [AboutController::class, 'update'])->name('updateabout');

        });  

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    // public $guarded = [];

    protected $fillable = ['name'];

    public function scopeWhereRoleNot($query, $role_name)
    {
        return $query->whereNotIn('name', (array)$role_name);
    }

    public function scopeIdDescending($query)
   {
        return $query->orderBy('id','DESC');
   }   
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreRole;
use Illuminate\Http\Request;
use App\Models\Role;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Validation\Rule;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:roles-read')->only(['index']);
        $this->middleware('permission:roles-create')->only(['create','store']);
        $this->middleware('permission:roles-update')->only(['edit','update']);
        $this->middleware('permission:roles-delete')->only(['destroy']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Role::idDescending()->whereRoleNot(['super_admin'])->with('permissions')->get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function($row){
            if (Auth::guard('admin')->user()->hasPermission('roles-update')){
             $btn ='<a href="' .route("roles.edit", $row->id). '" type="button" class="btn btn-info btn-icon"><i class="icofont icofont-pen-alt-4"></i></i></a> &nbsp;';
            }else{
             $btn = '<a  href="" class="btn btn-primary btn-xs disabled">Edit</i></a>';
            }
    
            if (Auth::guard('admin')->user()->hasPermission('roles-delete')){
                $btn = $btn.
                '<form class=" delete"  action="' . route("roles.destroy", $row->id) . '"  method="POST" id="delform"
                style="display: inline-block; right: 50px;" >
                <input name="_method" type="hidden" value="DELETE">
                <input type="hidden" name="_token" value="' . csrf_token() . '">
                <button type="submit" class="btn btn-danger btn-icon" title=" ' . 'Delete' . ' "><i class="icofont icofont-trash"></i></button>
                    </form>';
            }else{
                $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
            }
    
                        return $btn;
                    })
    
                    ->rawColumns(['action'])
                    ->make(true);
    
            }
    
            return view('admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $models = ['admins', 'roles','users','owners','aboutus','terms',
        'categories','advert','serv','order','bank','complaints',
        'country','contactus','settings'];

        $actions = ['create', 'read', 'update', 'delete'];
        return view('admin.roles.create',compact('models','actions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRole $request)
    {
        $role = Role::create($request->all());
        $role->attachPermissions($request->permissions);
        
        session()->flash('success', __('admin.addsuccessfully'));
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $models = ['admins', 'roles','users','owners','aboutus','terms',
        'categories','advert','serv','order','bank','complaints',
        'country','contactus','settings'];

        $actions = ['create', 'read', 'update', 'delete'];
        $role = Role::findOrFail($id);
        return view('admin.roles.edit',compact('role','models','actions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $request->validate([
            'name' => ['required',Rule::unique('roles')->ignore($id)],
            'permissions' => 'required|array|min:1',
        ]);

        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        session()->flash('success', __('admin.updatesuccessfully'));
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">

        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.dashboard') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.roles')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.addroles')</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.addroles')</h5>
                                </div>
                                <div class="card-block">
                                    <form action="{{route('roles.store')}}" method="post" data-parsley-validate>
                                        @csrf
                                        @method('post')

                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">@lang('admin.namerole')</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="name" value="{{old('name')}}" required
                                                    parsley-trigger="change" placeholder="@lang('admin.namerole')"
                                                    class="form-control form-control-round">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <table class="table">
                                                <tbody>
                                                    <tr>
                                                        <th style="width: 10px">#</th>
                                                        <th>@lang('admin.model')</th>
                                                        <th>@lang('admin.permissions')</th>
                                                    </tr>
                                                    @foreach($models as $index=>$model)
                                                    @if($model == 'settings')
                                                    <?php $actions = ['read', 'update']; ?>
                                                    @endif
                                                    @if($model == 'contactus')
                                                    <?php $actions = ['read', 'delete']; ?>
                                                    @endif
                                                    <tr>
                                                        <td style="width:5%">{{$index+1}}</td>
                                                        <td style="width:5%">@lang('admin.'.$model)</td>
                                                        <td class="col-sm-8 col-xl-4 m-b-30">
                                                            <select class="js-example-placeholder-multiple col-sm-8"
                                                                name="permissions[]" multiple="multiple">
                                                                @foreach($actions as $index=>$action)
                                                                <option value="{{$model.'-'.$action}}">
                                                                    @lang('admin.'.$action)</option>
                                                                @endforeach
                                                            </select>
                                                        </td>
                                                    </tr>
                                                    @endforeach

                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="form-group has-danger row">
                                            <div class="col-sm-10">
                                    <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                                    &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                                    <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- Basic Form Inputs card end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">

        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.dashboard') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.roles')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.editroles')</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.addroles')</h5>
                                </div>
                                <div class="card-block">
                                    <form action="{{route('roles.update',$role->id)}}" method="post" data-parsley-validate>
                                        @csrf
                                        @method('put')

                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">@lang('admin.namerole')</label>
                                            <div class="col-sm-10">
                                                <input type="text" name="name" value="{{$role->name}}" 
                                                required parsley-trigger="change"  placeholder="@lang('admin.namerole')"
                                                    class="form-control form-control-round">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <table class="table">
                                                <tbody>
                                                    <tr>
                                                        <th style="width: 10px">#</th>
                                                        <th>@lang('admin.model')</th>
                                                        <th>@lang('admin.permissions')</th>
                                                    </tr>
                                                    @foreach($models as $index=>$model)
                                                    @if($model == 'settings')
                                                    <?php $actions = ['read', 'update']; ?>
                                                    @endif
                                                    @if($model == 'contactus')
                                                    <?php $actions = ['read', 'delete']; ?>
                                                    @endif
                                                    <tr>
                                                        <td style="width:5%">{{$index+1}}</td>
                                                        <td style="width:5%">@lang('admin.'.$model)</td>
                                                        <td class="col-sm-8 col-xl-4 m-b-30">
                                                            <select class="js-example-placeholder-multiple col-sm-8"
                                                                name="permissions[]" multiple="multiple">
                                                                @foreach($actions as $index=>$action)

                                                                <option value="{{$model.'-'.$action}}" {{$role->hasPermission($model.'-'.$action) ? 'selected':''}}>@lang('admin.'.$action)</option>
                                                                @endforeach
                                                            </select>
                                                        </td>
                                                    </tr>
                                                    @endforeach

                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="form-group has-danger row">
                                            <div class="col-sm-10">
                                    <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                                    &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                                    <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- Basic Form Inputs card end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layout.master')

@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">

        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.dashboard') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.roles')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.roles')</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-10">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.roles')</h5>
                                </div>
                                <div class="card-block">
                                    <div class="dt-responsive table-responsive">
                                            <table  class="table table-striped table-bordered nowrap role-table">
                                                <thead>
                                                    <tr>
                                                        <th class="text-center">#</th>
                                                        <th class="text-center">@lang('admin.role')</th>
                                                        <th class="text-center"></th>
                                                    </tr>
                                                </thead>
                                            </table>
                                    </div>
                            </div>
                            <!-- Basic Form Inputs card end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@push('js')
<script>
 $(function () {

    var locale = '{{ config('app.locale') }}';
    if (locale == 'ar') {
    var table = $('.role-table').DataTable({
        "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"},
        processing: true,
        serverSide: true,

        ajax: "{{ route('roles.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name',searchable: true, sortable : true},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        responsive:true,
        searching: true,
        order:[0,'desc']
    }); 
        }else{

    var table = $('.role-table').DataTable({
        "language": {"url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"},
        processing: true,
        serverSide: true,
        ajax: "{{ route('roles.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name',searchable: true, sortable : true},
            {data: 'action', name: 'action', orderable: false, searchable: false},
        ],
        responsive:true,
        searching: true,
        order:[0,'desc']
    }); 
}  

    $('body').on('submit','#delform',function (e) {
        e.preventDefault();
        var url = $(this).attr('action');
        $.ajax({
          url: url,
          method: "delete",
          data: {
              _token: '{{ csrf_token() }}',
          },
          success: function (response) {
              if (response.status == 'success'){
                  new Noty({
                      type: 'success',
                      layout: 'topRight',
                      text: "@lang('admin.deletesuccessfully')",
                      timeout: 5000,
                      killer: true
                  }).show();
                  table.ajax.reload();
              }
          }
        });
        })
});    
</script>   


@endpush