routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\AdvertisingpackagesController;
use App\Http\Controllers\Admin\AdvertismentController;
use App\Http\Controllers\Admin\BannersController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\HelpController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CitiesController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PropagandaController;
use App\Http\Controllers\Admin\TermsController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::POST('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {


            Route::get('complaints', [ComplaintController::class, 'index'])->name('complaints');
            Route::delete('complaints/{id}', [ComplaintController::class, 'destroy'])->name('destroycomplaints');

            Route::resource('roles', RoleController::class)->except(['show']);

            Route::resource('services', ServicesController::class)->except(['show']);
            Route::get('serviceactive', [ServicesController::class, 'ServiceStatus'])->name('serviceactive');

            Route::resource('banners', BannersController::class)->except(['show']);
            Route::get('banneractive', [BannersController::class, 'BannerStatus'])->name('banneractive');

            Route::resource('advertisments', AdvertismentController::class)->except(['show']);
            Route::get('advertismentactive', [AdvertismentController::class, 'advertismentStatus'])->name('advertismentactive');

            Route::resource('admins', AdminsController::class)->except(['show']);
            Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

            Route::resource('cities', CitiesController::class)->except(['show']);
            Route::get('cityactive', [CitiesController::class, 'CityStatus'])->name('cityactive');
            
            Route::resource('packages', AdvertisingpackagesController::class)->except(['show']);
            Route::get('packageactive', [AdvertisingpackagesController::class, 'packageStatus'])->name('packageactive');

            Route::get('helps', [HelpController::class, 'index'])->name('helping');
            Route::post('helps', [HelpController::class, 'update'])->name('updatehelping');

            Route::get('terms', [TermsController::class, 'index'])->name('terming');
            Route::post('terms', [TermsController::class, 'update'])->name('updateterming');

            Route::get('propagandas', [PropagandaController::class, 'index'])->name('propaganding');
            Route::post('propagandas', [PropagandaController::class, 'update'])->name('updatepropaganding');

            Route::resource('users', UsersController::class)->except(['show']);
            Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');
            Route::get('useraddress', [UsersController::class, 'UserAddress'])->name('useraddress');

            Route::resource('owners', OwnerController::class);
            Route::get('owneractive', [OwnerController::class, 'OwnerStatus'])->name('owneractive');
           // Route::resource('balance/{id}', [BalanceOwnerController::class, 'destroy']);
            Route::get('ownersbalance/{id}',[OwnerController::class,'OwnersBalance'])->name('owners.balances');


            Route::resource('contactus', ContactController::class)->except(['create','edit']);


            Route::get('about', [AboutController::class, 'index'])->name('about');
            Route::post('about', [AboutController::class, 'update'])->name('updateabout');

        });  

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Advertisment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Advertisment extends Model
{
    use HasFactory;

    protected $fillable  = ['owner_id','package_id','active'];

}

app/Http/Controllers/Admin/AdvertismentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Advertisingpackage;
use App\Models\Advertisment;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Auth;
use App\Models\Owner;
use Illuminate\Http\Request;

class AdvertismentController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:advert-read')->only(['index']);
        $this->middleware('permission:advert-create')->only(['create','store']);
        $this->middleware('permission:advert-update')->only(['edit','update']);
        $this->middleware('permission:advert-delete')->only(['destroy']);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Advertisment::get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->editColumn('owner_id', function ($query) {
                $owner_name = Owner::where('id',$query->owner_id)->first();
                return $owner_name->name;
            })
            ->editColumn('package_id', function ($query) {
                $package = Advertisingpackage::where('id',$query->package_id)->first();
                return $package->period;
            })
            ->editColumn('active', function ($query) {
                if ($query->active) {
                    $btn = '
            <div align="center">
            <label class="switch">
            <input data-id="' . $query->id . '" type="checkbox" id="check" checked>
                <div class="slider round">
                    <span class="on">ON</span>
                    <span class="off">OFF</span>
                </div>
            </label>
          </div>';
                } else {
                    $btn = '
                <div align="center">
                <label class="switch">
                <input data-id="' . $query->id . '" type="checkbox" id="check">
                    <div class="slider round">
                        <span class="on">ON</span>
                        <span class="off">OFF</span>
                    </div>
                </label>
              </div>';
                }

                return $btn;
            })
            ->addColumn('action', function($row){
            if (Auth::guard('admin')->user()->hasPermission('advert-update')){
            $btn ='<a href="' .route("advertisments.edit", $row->id). '" type="button" class="btn btn-info btn-icon"><i class="icofont icofont-pen-alt-4"></i></i></a> &nbsp;';
            }else{
            $btn = '<a  href="" class="btn btn-primary btn-xs disabled">Edit</i></a>';
            }
    
            if (Auth::guard('admin')->user()->hasPermission('advert-delete')){
                $btn = $btn.
                '<form class="delete"  action="' . route("advertisments.destroy", $row->id) . '"  method="POST" id="delform"
                style="display: inline-block; right: 50px;" >
                <input name="_method" type="hidden" value="DELETE">
                <input type="hidden" name="_token" value="' . csrf_token() . '">
                <button type="submit" class="btn btn-danger btn-icon" title=" ' . 'Delete' . ' "><i class="icofont icofont-trash"></i></button>
                    </form>';
            }else{
                $btn = $btn. '<button class="btn btn-danger btn-xs disabled"><i class="fa fa-trash-o"></i></button>';
            }

                        return $btn;
                    })

                    ->rawColumns(['action','active'])
                    ->make(true);

            }
        return view('admin.advertisments.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $owners = Owner::get();
        $packages = Advertisingpackage::get();
        return view('admin.advertisments.create', compact('owners','packages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $owner = Advertisment::create([
            'owner_id'       => $request->input('owner_id'),
            'package_id'      => $request->input('package_id'),
        ]);

        $owner->save();

        return response()->json(['status'=>'success','data'=>$owner]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function advertismentStatus(Request $request)
    {
        $advertisment = Advertisment::find($request->ads_id);
        $advertisment->active = $request->active;
        $advertisment->save();
        
        return response()->json(['status' => 'success', 'data' => $advertisment]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $owners = Owner::get();
        $packages = Advertisingpackage::get();

        $advertisment = Advertisment::findOrFail($id);
        return view('admin.advertisments.edit', compact('owners','packages','advertisment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $advertisment = Advertisment::findOrFail($id);

        $advertisment->update([
            'owner_id'       => $request->input('owner_id'),
            'package_id'      => $request->input('package_id'),
        ]);

        $advertisment->save();
        return response()->json(['status'=>'success','data'=>$advertisment]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $advertisment = Advertisment::findOrFail($id);
        $advertisment->delete();
        return response()->json(['status'=>'success']);
    }
}

resources/views/admin/advertisments/create.blade.php
@extends('admin.layout.master')
@section('content')
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.adverts') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.adverts')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.addadverts')</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-10">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.addadverts')</h5>
                                </div>
                                <div class="card-block">
                                    <form id="advertisment" method="POST"  data-parsley-validate>
                                        @csrf
                                        @method('post')
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">@lang('admin.addadverts')</label>
                                            <div class="col-sm-10">
                                            <select id="hello-single" name="owner_id" class="form-control form-control-round">
                                                <option value="">---</option>
                                                @foreach ($owners as $owner)
                                                <option value="{{$owner->id}}">{{$owner->name}}</option>
                                                @endforeach
                                            </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">@lang('admin.advertperiod')</label>
                                            <div class="col-sm-10">
                                            <select id="hello-single" name="package_id" class="form-control form-control-round">
                                                <option value="">---</option>
                                                @foreach ($packages as $package)
                                                <option value="{{$package->id}}">{{$package->period}}</option>
                                                @endforeach
                                            </select>
                                            </div>
                                        </div>

                                        <div class="form-group has-danger row">
                                            <div class="col-sm-10">
                                    <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                                    &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                                    <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                            </div>
                                        </div>
                            </form>
                        </div>
                    </div>
                    <!-- Basic Form Inputs card end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page body end -->
@endsection


@push('js')
<script>
    $(function () {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('body').on('submit', '#advertisment', function (e) {
            e.preventDefault();
            // alert('asdasd');
            $.ajax({
                url: '{{ route('advertisments.store')}}',
                method: "post",
                data: new FormData(this),
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,

                success: function (response) {
                    //console.log(response);
                    if (response.status == 'success') {
                        new Noty({
                            type: 'success',
                            layout: 'topRight',
                            text: "@lang('admin.addsuccessfully')",
                            timeout: 5000,
                            killer: true
                        }).show();
                    }
                },
            });
        });

    });

</script>
@endpush

resources/views/admin/advertisments/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
            <div class="page-header">
                <div class="page-header-title">
                    <h4> @lang('admin.adverts') </h4>
                </div>
                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a href="">
                                <i class="icofont icofont-home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.adverts')</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.editadverts')</a>
                        </li>
                    </ul>
                </div>
            </div>
      <!-- Page body start -->
      <div class="page-body">
        <div class="row">
            <div class="col-sm-8">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>@lang('admin.editadvertisments')</h5>
                    </div>
                    <div class="card-block">
                        <form id="advertisment" method="POST" data-parsley-validate>
                            @csrf
                            @method('put')
                            <input type="hidden" name="AdvertismentsId" id="advertisments_id" value="{{$advertisment->id}}"  class="form-control">

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.addadverts')</label>
                                <div class="col-sm-10">
                                <select id="hello-single" name="owner_id" class="form-control form-control-round">
                                    <option value="">---</option>
                                    @foreach ($owners as $owner)
                                    <option value="{{$owner->id}}">{{$owner->name}}</option>
                                    @endforeach
                                </select>
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.advertperiod')</label>
                                <div class="col-sm-10">
                                <select id="hello-single" name="package_id" class="form-control form-control-round">
                                    <option value="">---</option>
                                    @foreach ($packages as $package)
                                    <option value="{{$package->id}}">{{$package->period}}</option>
                                    @endforeach
                                </select>
                                </div>
                            </div>

                            <div class="form-group has-danger row">
                                <div class="col-sm-10">
                        <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                        &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                        <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Basic Form Inputs card end -->
            </div>
        </div>
    </div>
    </div>
</div>

@endsection
@push('js')
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#advertisments',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#advertisments_id').val();
                 var url = '{{ route('advertisments.update', ':id') }}';
                 url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {
                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }

                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/advertisments/index.blade.php
@extends('admin.layout.master')
@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">

        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.adverts') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.adverts')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.adverts')</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.adverts')</h5>
                                </div>
                                <div class="card-block">
                                    <div class="dt-responsive table-responsive">
                                        <table class="table table-striped table-bordered city-table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">#</th>
                                                    <th class="text-center">@lang('admin.advertiser')</th>
                                                    <th class="text-center">@lang('admin.advertperiod')</th>
                                                    <th class="text-center">@lang('admin.active')</th>
                                                    <th class="text-center"></th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                                <!-- Basic Form Inputs card end -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')
<script>
    $(function () {

        var locale = '{{ config('
        app.locale ') }}';
        if (locale == 'ar') {
            var table = $('.city-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"
                },
                processing: true,
                serverSide: true,

                ajax: "{{ route('advertisments.index') }}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'owner_id',
                        name: 'owner_id',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'package_id',
                        name: 'package_id',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'active',
                        name: 'active',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
                responsive: true,
                searching: true,
                order: [0, 'desc']
            });
        } else {

            var table = $('.city-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"
                },
                processing: true,
                serverSide: true,
                ajax: "{{ route('advertisments.index') }}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'owner_id',
                        name: 'owner_id',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'package_id',
                        name: 'package_id',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'active',
                        name: 'active',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
                responsive: true,
                searching: true,
                order: [0, 'desc']
            });
        }

    $('body').on('click','#check',function () {
    //e.preventDefault();
    var active = $(this).prop('checked') == true ? 1 : 0; 
    var ads_id = $(this).data('id');
     $.ajax({
        url:'{{ route('advertismentactive') }}',
        type:'GET',
        data:{
            'active': active,
            'ads_id': ads_id
        },
         success: function (response) {
         if (response.status == 'success'){
             new Noty({
                type: 'success',
                layout: 'topRight',
                text: "@lang('admin.statuschange')",
                timeout: 5000,
                killer: true
              }).show();
            }
        }
    });
});


        $('body').on('submit', '#delform', function (e) {
            e.preventDefault();
            var url = $(this).attr('action');
            $.ajax({
                url: url,
                method: "delete",
                data: {
                    _token: '{{ csrf_token() }}',
                },
                success: function (response) {
                    if (response.status == 'success') {
                        new Noty({
                            type: 'success',
                            layout: 'topRight',
                            text: "@lang('users.deletesuccessfully')",
                            timeout: 5000,
                            killer: true
                        }).show();
                        table.ajax.reload();
                    }
                }
            });
        })
    });

</script>


@endpush