routes/admin.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminsController;
use App\Http\Controllers\Admin\AdvertisingpackagesController;
use App\Http\Controllers\Admin\AdvertismentController;
use App\Http\Controllers\Admin\BannersController;
use App\Http\Controllers\Admin\ComplaintController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\HelpController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CitiesController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\OwnerController;
use App\Http\Controllers\Admin\PropagandaController;
use App\Http\Controllers\Admin\TermsController;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::get('admin/home', [AdminController::class, 'index'])->name('adminhome');
        Route::GET('admin', [LoginController::class, 'showLoginForm'])->name('admin.login');
        Route::POST('admin',[LoginController::class, 'login']);
        Route::POST('logout',[LoginController::class, 'logout'])->name('admin.logout');

        Route::group(['prefix' => 'admin', 'middleware' => ['auth:admin']], function () {


            Route::get('complaints', [ComplaintController::class, 'index'])->name('complaints');
            Route::delete('complaints/{id}', [ComplaintController::class, 'destroy'])->name('destroycomplaints');

            Route::resource('roles', RoleController::class)->except(['show']);

            Route::resource('services', ServicesController::class)->except(['show']);
            Route::get('serviceactive', [ServicesController::class, 'ServiceStatus'])->name('serviceactive');

            Route::resource('banners', BannersController::class)->except(['show']);
            Route::get('banneractive', [BannersController::class, 'BannerStatus'])->name('banneractive');

            Route::resource('advertisments', AdvertismentController::class)->except(['show']);
            Route::get('advertismentactive', [AdvertismentController::class, 'advertismentStatus'])->name('advertismentactive');

            Route::resource('admins', AdminsController::class)->except(['show']);
            Route::get('adminactive', [AdminsController::class, 'AdminStatus'])->name('adminactive');

            Route::resource('cities', CitiesController::class)->except(['show']);
            Route::get('cityactive', [CitiesController::class, 'CityStatus'])->name('cityactive');
            
            Route::resource('packages', AdvertisingpackagesController::class)->except(['show']);
            Route::get('packageactive', [AdvertisingpackagesController::class, 'packageStatus'])->name('packageactive');

            Route::get('helps', [HelpController::class, 'index'])->name('helping');
            Route::post('helps', [HelpController::class, 'update'])->name('updatehelping');

            Route::get('terms', [TermsController::class, 'index'])->name('terming');
            Route::post('terms', [TermsController::class, 'update'])->name('updateterming');

            Route::get('propagandas', [PropagandaController::class, 'index'])->name('propaganding');
            Route::post('propagandas', [PropagandaController::class, 'update'])->name('updatepropaganding');

            Route::resource('users', UsersController::class)->except(['show']);
            Route::get('useractive', [UsersController::class, 'UserStatus'])->name('useractive');
            Route::get('useraddress', [UsersController::class, 'UserAddress'])->name('useraddress');

            Route::resource('owners', OwnerController::class);
            Route::get('owneractive', [OwnerController::class, 'OwnerStatus'])->name('owneractive');
           // Route::resource('balance/{id}', [BalanceOwnerController::class, 'destroy']);
            Route::get('ownersbalance/{id}',[OwnerController::class,'OwnersBalance'])->name('owners.balances');


            Route::resource('contactus', ContactController::class)->except(['create','edit']);


            Route::get('about', [AboutController::class, 'index'])->name('about');
            Route::post('about', [AboutController::class, 'update'])->name('updateabout');

        });  

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('command', function () {
    \Artisan::call('route:clear');
    \Artisan::call('config:clear');
    \Artisan::call('cache:clear');
    \Artisan::call('config:cache');
    
    });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/admins/create.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
       <div class="main-body">
        <div class="page-wrapper">
        <div class="page-header">
            <div class="page-header-title">
                <h4> @lang('admin.admins') </h4>
            </div>
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item">
                        <a href="">
                            <i class="icofont icofont-home"></i>
                        </a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">@lang('admin.admins')</a>
                    </li>
                    <li class="breadcrumb-item"><a href="#!">@lang('admin.addadmins')</a>
                    </li>
                </ul>
            </div>
        </div>

      <!-- Page body start -->
      <div class="page-body">
        <div class="row">
            <div class="col-sm-8">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>@lang('admin.addadmins')</h5>
                    </div>
                    <div class="card-block">
                        <form id="admins" method="POST" data-parsley-validate>
                            @csrf
                            @method('post')

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.name')</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" class="form-control form-control-round" placeholder="Enter Admin Name" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.email')</label>
                                <div class="col-sm-10">
                                    <input type="email" name="email" class="form-control form-control-round" placeholder="Enter Admin Email" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.password')</label>
                                <div class="col-sm-10">
                                    <input type="password" name="password" class="form-control form-control-round" placeholder="Enter Admin Password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.role')</label>
                                <div class="col-sm-10">
                                    <select class="form-control form-control-round" name="role_id" id="role_id" required>
                                     <option value="">---</option>
                                       @foreach($roles as $role)
                                        <option value="{{$role->id}}">{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group has-danger row">
                                <div class="col-sm-10">
                        <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                        &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                        <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Basic Form Inputs card end -->
            </div>
       </div>
    </div>
  </div>
</div>

@endsection

@push('js')
<script>
    $(".toggle-password").click(function() {
    $(this).toggleClass("fa-eye fa-eye-slash");
        var input = $($(this).attr("toggle"));
            if (input.attr("type") == "password") {
            input.attr("type", "text");
            } else {
            input.attr("type", "password");
            }
    });
</script>

<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#admins',function (e) {
                e.preventDefault();
                //  alert('asdasd');
                $.ajax({
                    url: '{{ route('admins.store')}}',
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        // console.log(response);
                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.addsuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/admins/edit.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
            <div class="page-header">
                <div class="page-header-title">
                    <h4> @lang('admin.admins') </h4>
                </div>
                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a href="">
                                <i class="icofont icofont-home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.admins')</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">@lang('admin.editadmins')</a>
                        </li>
                    </ul>
                </div>
            </div>
      <!-- Page body start -->
      <div class="page-body">
        <div class="row">
            <div class="col-sm-8">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>@lang('admin.editadmins')</h5>
                    </div>
                    <div class="card-block">
                        <form id="admins" method="POST" data-parsley-validate>
                            @csrf
                            @method('put')
                            <input type="hidden" name="AdminId" id="admin_id" value="{{$admin->id}}"  class="form-control">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.name')</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" value="{{$admin->name}}" class="form-control form-control-round" placeholder="Enter Admin Name" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.email')</label>
                                <div class="col-sm-10">
                                    <input type="email" name="email" value="{{$admin->email}}"  class="form-control form-control-round" placeholder="Enter Admin Email" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.password')</label>
                                <div class="col-sm-10">
                                    <input type="password" name="password" value="{{old('password')}}"  class="form-control form-control-round" placeholder="Enter Admin Password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">@lang('admin.role')</label>
                                <div class="col-sm-10">
                                    <select class="form-control form-control-round" name="role_id" id="role_id" required>
                                     <option value="">---</option>
                                       @foreach($roles as $role)
                                       <option  value="{{$role->id}}" {{$admin->hasRole($role->name) == 'true'? 'selected':''}}>{{$role->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group has-danger row">
                                <div class="col-sm-10">
                        <button class="btn btn-info btn-round" type="submit" name="submit" style="float: right;">@lang('admin.save')</button>
                        &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;
                        <a href="{{url()->previous()}}" class="btn btn-danger btn-round" style="margin-left: 30px;">@lang('admin.cancel')</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Basic Form Inputs card end -->
            </div>
        </div>
    </div>
    </div>
</div>

@endsection
@push('js')
<script>
    $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('body').on('submit','#admins',function (e) {
                e.preventDefault();
                 //alert('asdasd');
                 let id = $('#admin_id').val();
                 var url = '{{ route('admins.update', ':id') }}';
                 url = url.replace(':id', id);
                $.ajax({
                    url: url,
                    method: "post",
                    data: new FormData(this),
                    dataType: 'json',
                    cache       : false,
                    contentType : false,
                    processData : false,

                    success: function (response) {
                        //console.log(response);
                        if (response.errors){
                            $.each(response.errors, function( index, value ) {
                                new Noty({
                                    type: 'success',
                                    layout: 'topRight',
                                    text: value,
                                    timeout: 2000,
                                    killer: true
                                }).show();
                            });
                        }

                        if(response.status == 'success'){
                            new Noty({
                                type: 'success',
                                layout: 'topRight',
                                text: "@lang('admin.updatesuccessfully')",
                                timeout: 5000,
                                killer: true
                            }).show();
                        }
                    },

                });
            });

        });
 </script>
@endpush

resources/views/admin/admins/index.blade.php
@extends('admin.layout.master')

@section('content')

<div class="pcoded-content">
    <div class="pcoded-inner-content">

        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-header">
                    <div class="page-header-title">
                        <h4> @lang('admin.admins') </h4>
                    </div>
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="">
                                    <i class="icofont icofont-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.admins')</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#!">@lang('admin.admins')</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-header">
                                    <h5>@lang('admin.admins')</h5>
                                </div>
                                <div class="card-block">
                                    <div class="dt-responsive table-responsive">
                                        <table class="table table-striped table-bordered nowrap admin-table">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">#</th>
                                                    <th class="text-center">@lang('admin.admins')</th>
                                                    <th class="text-center">@lang('admin.email')</th>
                                                    <th class="text-center">@lang('admin.role')</th>
                                                    <th class="text-center">@lang('admin.active')</th>
                                                    <th class="text-center"></th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </div>
                                </div>
                                <!-- Basic Form Inputs card end -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('js')
<script>
    $(function () {

        var locale = '{{ config(' app.locale ') }}';
        if (locale == 'ar') {
            var table = $('.admin-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Arabic.json"
                },
                processing: true,
                serverSide: true,

                ajax: "{{ route('admins.index') }}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'name',
                        name: 'name',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'email',
                        name: 'email',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'role_id',
                        name: 'role_id'
                    },
                    {
                        data: 'active',
                        name: 'active',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
                responsive: true,
                searching: true,
                order: [0, 'desc']
            });

        } else {

            var table = $('.admin-table').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/English.json"
                },
                processing: true,
                serverSide: true,

                ajax: "{{ route('admins.index') }}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'name',
                        name: 'name',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'email',
                        name: 'email',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'role_id',
                        name: 'role_id'
                    },
                    {
                        data: 'active',
                        name: 'active',
                        orderable: false,
                        searchable: false
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ],
                responsive: true,
                searching: true,
                order: [0, 'desc']
            });
        }


        $('body').on('click','#check',function () {
    //e.preventDefault();
    var active = $(this).prop('checked') == true ? 1 : 0; 
    var admin_id = $(this).data('id');
     $.ajax({
        url:'{{ route('adminactive') }}',
        type:'GET',
        data:{
            'active':active,
            'admin_id': admin_id
        },
         success: function (response) {
         if (response.status == 'success'){
             new Noty({
                type: 'success',
                layout: 'topRight',
                text: "@lang('admin.statuschange')",
                timeout: 5000,
                killer: true
              }).show();
            }
        }
    });
});



        $('body').on('submit', '#delform', function (e) {
            e.preventDefault();
            var url = $(this).attr('action');
            $.ajax({
                url: url,
                method: "delete",
                data: {
                    _token: '{{ csrf_token() }}',
                },
                success: function (response) {
                    if (response.status == 'success') {
                        new Noty({
                            type: 'success',
                            layout: 'topRight',
                            text: "@lang('admin.deletesuccessfully')",
                            timeout: 5000,
                            killer: true
                        }).show();
                        table.ajax.reload();
                    }
                }
            });
        })
    });

</script>


@endpush